name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Typecheck (optional)
        run: bun run typecheck --if-present

      - name: Lint (optional)
        run: bun run lint --if-present

      - name: Test (optional)
        run: bun run test --if-present

      - name: Build (optional)
        run: bun run build --if-present
